homework #3 cloud-bastion result
Otus-DevOps-2019-11/lukinpvl_infra pull request #2
Opened 2019-12-22 15:45 UTC by lukinpvl

# Выполнено ДЗ №

 - [x] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
 - Создана учетная запись GCP
 - Созданы 2 ВМ: bastion и someinternalhost
 - Настроен VPN сервер на ВМ bastion

## Как запустить проект:
 - неприменимо

## Как проверить работоспособность:
 - неприменимо

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [x] Выставил label с темой домашнего задания

2019-12-22 20:01 UTC, mrgreyves requested changes
Здравствуйте!) На момент тестов ВМ были включены? Ошибка связана именно с невозможность подключения =(

2019-12-22 20:01 UTC, mrgreyves commented on README.md
> +    	User appuser
Еще в конфигурации можно указать с каким ключом подключаться =)

2019-12-23 08:12 UTC, lukinpvl commented on README.md
> +    	User appuser
Поправил файл README.md. Указал ключ

2019-12-23 09:26 UTC, mrgreyves approved these changes
Здравствуйте!) Логи тревиса не нужно прикладывать к дз. Принимаю!)

2019-12-23 09:36 UTC, lukinpvl commented
> е!) Логи тревиса не нужно прикладывать к дз. Принимаю!)

Каким действием я их приложил?

2019-12-23 09:37 UTC, merged